//Работа с ингредиентами в конструкторе
export const ADD_INGREDIENT_TO_CONSTRUCTOR = 'ADD_INGREDIENT_TO_CONSTRUCTOR';
export const REMOVE_INGREDIENT_FROM_CONSTRUCTOR = 'REMOVE_INGREDIENT';
export const MOVE_INGREDIENTS = 'MOVE_INGREDIENT';